/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Org controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { CreateOrg, RequestOptions, Org, OrgVecObj } from "../models";

@Injectable({ providedIn: "root" })
export class OrgService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    upsert(createOrg: CreateOrg, observe?: 'body', options?: RequestOptions<'json'>): Observable<Org>;
    upsert(createOrg: CreateOrg, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Org>>;
    upsert(createOrg: CreateOrg, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Org>>;
    upsert(createOrg: CreateOrg, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v0/org`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, createOrg, requestOptions);
    }

    remove(name: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    remove(name: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    remove(name: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    remove(name: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v0/org/${name}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }

    readMany(observe?: 'body', options?: RequestOptions<'json'>): Observable<OrgVecObj>;
    readMany(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<OrgVecObj>>;
    readMany(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<OrgVecObj>>;
    readMany(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v0_public/org`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    read(name: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<Org>;
    read(name: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Org>>;
    read(name: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Org>>;
    read(name: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v0_public/org/${name}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }
}
