/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Profile controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { CreateProfile, RequestOptions, Profile, ProfileVecObj } from "../models";

@Injectable({ providedIn: "root" })
export class ProfileService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    upsert(createProfile: CreateProfile, observe?: 'body', options?: RequestOptions<'json'>): Observable<Profile>;
    upsert(createProfile: CreateProfile, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Profile>>;
    upsert(createProfile: CreateProfile, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Profile>>;
    upsert(createProfile: CreateProfile, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v0/profile`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, createProfile, requestOptions);
    }

    remove(observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    remove(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    remove(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    remove(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v0/profile`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }

    read(observe?: 'body', options?: RequestOptions<'json'>): Observable<Profile>;
    read(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Profile>>;
    read(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Profile>>;
    read(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v0_public/profile`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    readMany(observe?: 'body', options?: RequestOptions<'json'>): Observable<ProfileVecObj>;
    readMany(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ProfileVecObj>>;
    readMany(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ProfileVecObj>>;
    readMany(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v0_public/profiles`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }
}
