/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Repo controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { CreateRepo, RequestOptions, Repo, RepoVecObj } from "../models";

@Injectable({ providedIn: "root" })
export class RepoService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    upsert(org: string, createRepo: CreateRepo, observe?: 'body', options?: RequestOptions<'json'>): Observable<Repo>;
    upsert(org: string, createRepo: CreateRepo, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Repo>>;
    upsert(org: string, createRepo: CreateRepo, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Repo>>;
    upsert(org: string, createRepo: CreateRepo, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v0/org/${org}/repo`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, createRepo, requestOptions);
    }

    remove(org: any, name: any, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    remove(org: any, name: any, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    remove(org: any, name: any, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    remove(org: any, name: any, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v0/org/${org}/repo/${name}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.delete(url, requestOptions);
    }

    readMany(org: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<RepoVecObj>;
    readMany(org: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<RepoVecObj>>;
    readMany(org: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<RepoVecObj>>;
    readMany(org: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v0_public/org/${org}/repo`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    read(org: any, name: any, observe?: 'body', options?: RequestOptions<'json'>): Observable<Repo>;
    read(org: any, name: any, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Repo>>;
    read(org: any, name: any, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Repo>>;
    read(org: any, name: any, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v0_public/org/${org}/repo/${name}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }
}
