/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for RepoHistory controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { CreateRepoHistory, RequestOptions, RepoHistory, RepoHistoryVecObj } from "../models";

@Injectable({ providedIn: "root" })
export class RepoHistoryService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    upsert(org: any, repo: any, createRepoHistory: CreateRepoHistory, observe?: 'body', options?: RequestOptions<'json'>): Observable<RepoHistory>;
    upsert(org: any, repo: any, createRepoHistory: CreateRepoHistory, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<RepoHistory>>;
    upsert(org: any, repo: any, createRepoHistory: CreateRepoHistory, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<RepoHistory>>;
    upsert(org: any, repo: any, createRepoHistory: CreateRepoHistory, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v0/org/${org}/repo/${repo}/history`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, createRepoHistory, requestOptions);
    }

    readMany(org: any, repo: any, observe?: 'body', options?: RequestOptions<'json'>): Observable<RepoHistoryVecObj>;
    readMany(org: any, repo: any, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<RepoHistoryVecObj>>;
    readMany(org: any, repo: any, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<RepoHistoryVecObj>>;
    readMany(org: any, repo: any, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v0_public/org/${org}/repo/${repo}/history`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    read(org: any, repo: any, hash: any, observe?: 'body', options?: RequestOptions<'json'>): Observable<RepoHistory>;
    read(org: any, repo: any, hash: any, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<RepoHistory>>;
    read(org: any, repo: any, hash: any, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<RepoHistory>>;
    read(org: any, repo: any, hash: any, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v0_public/org/${org}/repo/${repo}/history/${hash}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }
}
