/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for RunHistory controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { CreateRunHistory, RequestOptions, RunHistory, RunHistoryVecObj } from "../models";

@Injectable({ providedIn: "root" })
export class RunHistoryService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    upsert(org: any, repo: any, createRunHistory: CreateRunHistory, observe?: 'body', options?: RequestOptions<'json'>): Observable<RunHistory>;
    upsert(org: any, repo: any, createRunHistory: CreateRunHistory, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<RunHistory>>;
    upsert(org: any, repo: any, createRunHistory: CreateRunHistory, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<RunHistory>>;
    upsert(org: any, repo: any, createRunHistory: CreateRunHistory, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v0/org/${org}/repo/${repo}/run`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.post(url, createRunHistory, requestOptions);
    }

    readMany(org: any, repo: any, observe?: 'body', options?: RequestOptions<'json'>): Observable<RunHistoryVecObj>;
    readMany(org: any, repo: any, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<RunHistoryVecObj>>;
    readMany(org: any, repo: any, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<RunHistoryVecObj>>;
    readMany(org: any, repo: any, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v0_public/org/${org}/repo/${repo}/run`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    read(org: any, repo: any, run: any, observe?: 'body', options?: RequestOptions<'json'>): Observable<RunHistory>;
    read(org: any, repo: any, run: any, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<RunHistory>>;
    read(org: any, repo: any, run: any, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<RunHistory>>;
    read(org: any, repo: any, run: any, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/v0_public/org/${org}/repo/${repo}/run/${run}`;

        const requestOptions: any = {
            observe: observe as any,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }
}
